# ASP.NET Core
# Build and test ASP.NET Core web applications targeting .NET Core.
# Add steps that run tests, create a NuGet package, deploy, and more:
# https://docs.microsoft.com/vsts/pipelines/languages/dotnet-core

pool:
  vmImage: 'VS2017-Win2016'

variables:
  buildConfiguration: 'Release'

steps:
- script: dotnet build --configuration $(buildConfiguration)
  displayName: 'dotnet build $(buildConfiguration)'

- script: dotnet test StrikesLibrary.Test\StrikesLibrary.Test.csproj --logger trx --collect "Code coverage"
- script: dotnet test StrikesRepository.Test\StrikesRepository.Test.csproj --logger trx --collect "Code coverage"
- script: dotnet test StrikesIntegration.Test\StrikesIntegration.Test.csproj --logger trx --collect "Code coverage"
- task: PublishTestResult@2
  inputs:
    testRunner: VSTest
    testResultsFiles: '**/*.trx'

- task: DotNetCoreCLI@2
  inputs:
    command: publish
    arguments: '--configuration $(buildConfiguration) --output $(Build.ArtifactStagingDirectory)'
    publishWebProjects: false
    zipAfterPublish: true

- task: PublishBuildArtifacts@1

